import { Role } from '../users/user.interface';

export const ROLES: Role[] = [
  {
    name: 'admin',
    permissions: {
      users: { canAdd: true, canEdit: true, canView: true, canDelete: true },
      roles: { canAdd: true, canEdit: true, canView: true, canDelete: true },
      organizations: { canAdd: true, canEdit: true, canView: true, canDelete: true },
      staffs: { canAdd: true, canEdit: true, canView: true, canDelete: true },
      transactions: { canAdd: true, canEdit: true, canView: true, canDelete: true },
      documents: { canAdd: true, canEdit: true, canView: true, canDelete: true },
      accounts: { canAdd: true, canEdit: true, canView: true, canDelete: true },
      profile: { canAdd: true, canEdit: true, canView: true, canDelete: true },
      'cashback-schemes': { canAdd: true, canEdit: true, canView: true, canDelete: true },
      reports: { canAdd: true, canEdit: true, canView: true, canDelete: true },
      'audit-logs': { canAdd: true, canEdit: true, canView: true, canDelete: true },
      cards: { canAdd: true, canEdit: true, canView: true, canDelete: true },
    },
  },
  {
    name: 'editor',
    permissions: {
      users: { canAdd: true, canEdit: true, canView: true, canDelete: false },
      roles: { canAdd: false, canEdit: true, canView: true, canDelete: false },
      organizations: { canAdd: false, canEdit: true, canView: true, canDelete: false },
      staffs: { canAdd: true, canEdit: true, canView: true, canDelete: false },
      transactions: { canAdd: true, canEdit: true, canView: true, canDelete: false },
      documents: { canAdd: true, canEdit: true, canView: true, canDelete: false },
      accounts: { canAdd: true, canEdit: true, canView: true, canDelete: false },
      profile: { canAdd: true, canEdit: true, canView: true, canDelete: false },
      'cashback-schemes': { canAdd: true, canEdit: true, canView: true, canDelete: false },
      reports: { canAdd: true, canEdit: true, canView: true, canDelete: false },
      'audit-logs': { canAdd: false, canEdit: false, canView: true, canDelete: false },
      cards: { canAdd: true, canEdit: true, canView: true, canDelete: false },
    },
  },
  {
    name: 'viewer',
    permissions: {
      users: { canAdd: false, canEdit: false, canView: true, canDelete: false },
      roles: { canAdd: false, canEdit: false, canView: true, canDelete: false },
      organizations: { canAdd: false, canEdit: false, canView: true, canDelete: false },
      staffs: { canAdd: false, canEdit: false, canView: true, canDelete: false },
      transactions: { canAdd: false, canEdit: false, canView: true, canDelete: false },
      documents: { canAdd: false, canEdit: false, canView: true, canDelete: false },
      accounts: { canAdd: false, canEdit: false, canView: true, canDelete: false },
      profile: { canAdd: false, canEdit: false, canView: true, canDelete: false },
      'cashback-schemes': { canAdd: false, canEdit: false, canView: true, canDelete: false },
      reports: { canAdd: false, canEdit: false, canView: true, canDelete: false },
      'audit-logs': { canAdd: false, canEdit: false, canView: true, canDelete: false },
      cards: { canAdd: false, canEdit: false, canView: true, canDelete: false },
    },
  },
];