import { Permission, Role } from '../users/user.interface';

export const ROLES: Role[] = [
  {
    name: 'admin',
    permissions: {
      nav_dashboard: Permission.allowInteraction,
      nav_organization: Permission.allowInteraction,
      nav_users: Permission.allowInteraction,
      nav_staff: Permission.allowInteraction,
      nav_transaction: Permission.allowInteraction,
      nav_cashBackScheme: Permission.allowInteraction,
      nav_cards: Permission.allowInteraction,
      nav_reports: Permission.allowInteraction,
      nav_auditLogs: Permission.allowInteraction,
      opt_searchMenu: Permission.allowInteraction,
      opt_profile: Permission.allowInteraction,
      opt_logout: Permission.allowInteraction,
      organization_add: Permission.allowInteraction,
      organization_edit: Permission.allowInteraction,
      organization_view: Permission.allowInteraction,
      organization_delete: Permission.allowInteraction,
      user_add: Permission.allowInteraction,
      user_edit: Permission.allowInteraction,
      user_view: Permission.allowInteraction,
      user_delete: Permission.allowInteraction,
      staff_add: Permission.allowInteraction,
      staff_edit: Permission.allowInteraction,
      staff_view: Permission.allowInteraction,
      staff_delete: Permission.allowInteraction,
      cashbackScheme_add: Permission.allowInteraction,
      cashbackScheme_edit: Permission.allowInteraction,
      cashbackScheme_view: Permission.allowInteraction,
      transaction_view: Permission.allowInteraction,
      documents_view: Permission.allowInteraction,
      documents_add: Permission.allowInteraction,
      accounts_view: Permission.allowInteraction,
      cards_add: Permission.allowInteraction,
      cards_edit: Permission.allowInteraction,
      cards_view: Permission.allowInteraction,

    },
  },
  {
    name: 'basic',
    permissions: {
      nav_dashboard: Permission.allowInteraction,
      nav_organization: Permission.blocked,
      nav_transaction: Permission.allowInteraction,
      nav_cashBackScheme: Permission.blocked,
      nav_cards: Permission.allowInteraction,
      nav_reports: Permission.allowInteraction,
      nav_auditLogs: Permission.blocked,
      opt_searchMenu: Permission.allowInteraction,
      opt_profile: Permission.allowInteraction,
      opt_logout: Permission.allowInteraction
    },
  },
  {
    name: 'viewer',
    permissions: {
      nav_dashboard: Permission.allowInteraction,
      nav_organization: Permission.allowInteraction,
      nav_transaction: Permission.allowInteraction,
      nav_cashBackScheme: Permission.allowInteraction,
      nav_cards: Permission.allowInteraction,
      nav_reports: Permission.allowInteraction,
      nav_auditLogs: Permission.allowInteraction,
      opt_searchMenu: Permission.allowInteraction,
      opt_profile: Permission.allowInteraction,
      opt_logout: Permission.allowInteraction
    },
  },
];